apiVersion: 1

datasources:
  - name: Prometheus - Local
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true

  - name: Loki - Local
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Tempo - Local
    type: tempo
    access: proxy
    url: http://tempo:3201
    editable: true
