name: pulse_rs_environment
services:
  prometheus:
    image: prom/prometheus:v3.0.1
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3

  loki:
    image: grafana/loki:3.2.2
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
    healthcheck:
        test: ["CMD", "wget", "-O-", "--no-verbose", "http://loki:3100/ready"]
        interval: 10s
        timeout: 5s
        retries: 3

  tempo:
    image: grafana/tempo:main-a170b4a # latest tag at the time of writing
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - 3200:3200
      - 3201:3201
    healthcheck:
      test: ["CMD", "wget", "-O-", "--no-verbose", "http://tempo:3201/ready"]
      interval: 10s
      timeout: 5s
      retries: 3

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.115.1
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
    ports:
      - 4317:4317
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
      tempo:
        condition: service_healthy

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - 13000:13000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=13000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini